services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - iamp-app
    ports:
      - "3000:3000"

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: mssql
    environment:
      SA_PASSWORD: "admin123!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -U sa -P "admin123!" -C -Q "SELECT 1" -b -o /dev/null
      start_period: 10s
      timeout: 2s
      interval: 30s
      retries: 3
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      - iamp-app

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - iamp-app
    ports:
      - "8000:8000"
    depends_on:
      - db
    entrypoint: ["/bin/bash", "/code/entrypoint.sh"]
    environment:
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}

networks:
  iamp-app:
    driver: bridge

volumes:
  mssql-data: