services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - iamp-app
    ports:
      - ${FE_HOST_MACHINE_PORT}:${FE_DOCKER_CONTAINER_PORT}
    env_file:
      - /.env

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: mssql
    environment:
      SA_PASSWORD: ${DB_PASSWORD}
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -U sa -P ${DB_PASSWORD} -C -Q "SELECT 1" -b -o /dev/null
      start_period: 10s
      timeout: 2s
      interval: 30s
      retries: 3
    ports:
      - ${DB_HOST_MACHINE_PORT}:${DB_DOCKER_CONTAINER_PORT}
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      - iamp-app
    env_file:
      - /.env

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - iamp-app
    ports:
      - "8000:8000"
    depends_on:
      - db
    entrypoint: ["/bin/bash", "/code/entrypoint.sh"]
    environment:
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
    env_file:
      - /.env

networks:
  iamp-app:
    driver: bridge

volumes:
  mssql-data: