services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - iamp-app
    ports:
      - "3000:3000"

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: mssql
    environment:
      SA_PASSWORD: "admin123!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      - iamp-app

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - iamp-app
    ports:
      - "8000:8000"
    depends_on:
      - db
    entrypoint: ["/bin/bash", "/code/entrypoint.sh"]
    environment:
      - SENDGRID_API_KEY=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

networks:
  iamp-app:
    driver: bridge

volumes:
  mssql-data: